[phases.setup]
nixPkgs = ["nodejs_18", "pkg-config", "cairo", "pango", "libpng", "libjpeg", "giflib", "librsvg", "pixman", "fontconfig", "freetype"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node app.js"